### ISSUE TITLE
initialize credential failed (?)

### ISSUE THREAD

**Issue by akimabs** [Saranshmalik/react-native-zendesk#28]
Hi, @Saranshmalik i just use your great package but i have small problem with it

react-native-zendesk-v2@^0.2.2

i initialize with this code
  ```
RNZendeskChat.init({
      key:
        Platform.OS === 'android'
          ? 'myandroidcredential='
          : 'myioscredential=',
      url: 'https://myurl.zendesk.com',
      appId: 'appid123123',
      clientId: 'mobile_Sdk',
    });
```

yes, ios and android both show this chat and help center screen, but both of them is nothing happen when chat and show the help center. can u help me solve my problem ? thanks before...

**Comment by akimabs** [comment]
i just following [this issue](https://github.com/Saranshmalik/react-native-zendesk/issues/8) and [this](https://github.com/Saranshmalik/react-native-zendesk/issues/25) but noting happen

**Comment by akimabs** [comment]
@saransh-malik or can u help me ?

**Comment by Saranshmalik** [comment]
Two things, first make sure your keys are correct. Chat keys should be
correct or nothing works, try opening debugger for the app either in Xcode
or Android Studio and you should see the Zendesk throwing logs in case
those are wrong.

Secondly before starting the chat you need to set user identity which is
step 2 of docs.

Also since you are using init method is your zendesk plan having answer bot
purchased, it doesn't work w/o that and in case you want just chat you need
to switch to other initChat method and use chatOnly:true while starting the
chat.

Please ensure all these steps, I use the library in a
production environment and the library works just fine, it would be an
issue on your implementation part.

**Comment by akimabs** [comment]
hi @Saranshmalik i have already at the chat with bot android and iOS have working great, thanks!

but at the Help Center when i open it and they navigate to the chat page.

any sugestion with this ?

**Comment by akimabs** [comment]
thanks @Saranshmalik my issue already solved, cause not setVisitorInfo at the showHelpCenter

**Comment by akimabs** [comment]
@Saranshmalik @saransh-malik hi where we can store the firebase key for the push notification ?

firebase store is not defined at the dashboard and i cant find where to store it
